services :
  frontend :
    container_name : azuracast_frontend
    build :
      context : .
    user : "${PUID:-1000}:${PGID:-1000}"
    volumes :
      - .:/data/frontend
      - ../resources/locale:/data/resources/locale
      - ../web/static:/data/web/static
      - frontend_node_modules:/data/frontend/node_modules

volumes :
  frontend_node_modules : { }
